# Generated by Django 5.0.4 on 2024-05-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0002_alter_book_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(db_table='Author2Book', related_name='books', to='booktest.author'),
        ),
    ]
